<?php 
    $semana1 = [
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-1", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"]
    ];

    $semana2 = [
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-2", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"]
    ];

    $semana3 = [
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-3", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"]
    ];

    $semana4 = [
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["SEMANA-4", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"]
    ];

    $semana5 = [
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"],
        ["SEMANA-5", "BIOLOGIA", "ARQUITETURA", "MICRO", "MIDIAS", "EMPREENDED", "QUIMICA"]
    ];

    $semana6 = [
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"],
        ["SEMANA-6", "QUIMICA", "ARQUITETURA", "ALGORITIMOS", "MICROINGO", "MIDIAS", "MANUTENÇÃO"]
    ];



?>