<?php 
    $semana1 = [
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."]
    ];

    $semana2 = [
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"]
    ];

    $semana3 = [
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["PORTUGUES", "MATEMATICA", "HISTORIA", "GEOGRAFIA", "BIOLOGIA", "FISICA", "QUIMICA"],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."],
        ["LP", "REDES", "WEB", "MOBILE", "MANUTENÇÃO", "EMPREENDEDORISMO", "S.O."]
    ];


?>